# The URL the site will be built for
base_url = "https://research-software.uit.no"

title = "Research software engineering group at UiT"

description = '''
Our vision is to put UiT on the map as a place where research groups have
access to best in class RSE services. Over time we wish to attract excellent
staff, research groups, funding, collaborations, and attention.
'''

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false


[markdown]

highlight_code = true
highlight_theme = "cheerfully-light"


[extra]

navigation = [
  { name = "Home", path = "/" },
  { name = "About us", path = "/about/" },
  { name = "Courses", path = "/courses/" },
  { name = "Blog", path = "/blog/" },
]

twitter_image = "https://raw.githubusercontent.com/uit-no/rse/main/content/logo1.png"
